apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: localstack
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds
      key: creds

  # Required for LocalStack in many setups
  skip_credentials_validation: true
  skip_requesting_account_id: true
  skip_metadata_api_check: true

  endpoint:
    url:
      type: Static
      static: http://localstack.devopstest.svc.cluster.local:4566
    services:
      - sns
      - sqs
      - dynamodb
      - sts

