apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.consumer.replicas }}
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      containers:
        - name: consumer
          image: {{ .Values.consumer.image }}
          env:
            - name: CLOUD_AWS_DEFAULTS_ENDPOINT
              value: {{ .Values.localstackEndpoint | quote }}

