apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.producer.replicas }}
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      containers:
        - name: producer
          image: {{ .Values.producer.image }}
          env:
            - name: CLOUD_AWS_DEFAULTS_ENDPOINT
              value: {{ .Values.localstackEndpoint | quote }}

