replicaCount: 2

image:
  repository: registry.tunoo.de/hello-app
  tag: latest
  pullPolicy: IfNotPresent
  imagePullSecrets: 
    - name: nexus-registry-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
metrics:
  port: 8090
  targetport: 8090

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

