apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-app-hello-world
  namespace: hello-app
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: "sourceip/32"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - hello.domain.tld
    secretName: my-tls-secret
  rules:
    - host: hello.domain.tld
      http:
        paths:
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: hello-app-hello-world
                port:
                  name: metrics
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-app-hello-world
                port:
                  name: http

